;;; eshell-aliases.el -*- lexical-binding: t; -*-
(defun eshell-add-aliases ()
  (dolist (var '(("gits" "git status")
                 ("system-upgrade" "sudo apt-get update && sudo apt-get -y upgrade")
                 ("tmux" "TERM=xterm-256color tmux")
                 ("reload" "source ~/.bashrc")
                 ("clip" "xclip -selection clipboard")
                 ("reload-wp" "feh --bg-max '/home/hpoe/Pictures/imperial-guard-standing.jpg'")
                 ("tf" "terraform")
                 ("tfd" "terraform destroy")
                 ("tfa" "terraform apply")
                 ("tfaa" "terraform apply -auto-approve")
                 ("tfda" "terraform destroy -auto-approve")
                 ("tfv" "terraform validate")
                 ("tfdoc" "terraform-docs .")
                 ("tfget" "terraform get --update")
                 ("tffmt" "terraform fmt")
                 ("tfout" "terraform output")
                 ("gits" "git status")
                 ("gitadd" "git add -A")
                 ("gitd" "git diff")
                 ("gitc" "git commit -m")
                 ("gitp" "git push")
                 ("pfind" "find . -type f | xargs grep -n")
                 ("gsed" "sed")
                 ))
    (add-to-list 'eshell-command-aliases-list var)))
(add-hook 'eshell-post-command-hook 'eshell-add-aliases)
